const PHASES = [
  {id:'p0', label:'Fase 0 — Base sólida', color:'#00e5a0', period:'Meses 1–4', items:[
    {id:'p0_01',text:'Redes: modelo OSI e TCP/IP',tag:'teoria'},
    {id:'p0_02',text:'Redes: endereçamento IP e sub-redes',tag:'teoria'},
    {id:'p0_03',text:'Redes: VLANs, DNS e DHCP',tag:'teoria'},
    {id:'p0_04',text:'Redes: roteamento e firewall',tag:'teoria'},
    {id:'p0_05',text:'Python: variáveis, tipos, condicionais e loops',tag:'lab'},
    {id:'p0_06',text:'Python: funções, listas e dicionários',tag:'lab'},
    {id:'p0_07',text:'Python: leitura e escrita de arquivos',tag:'lab'},
    {id:'p0_08',text:'Python: módulos e tratamento de erros',tag:'lab'},
    {id:'p0_09',text:'Linux: navegação, permissões e usuários',tag:'lab'},
    {id:'p0_10',text:'Linux: scripts bash, cron jobs e systemd',tag:'lab'},
    {id:'p0_11',text:'SQL: SELECT, WHERE, GROUP BY e ORDER BY',tag:'lab'},
    {id:'p0_12',text:'SQL: JOINs, subqueries e índices',tag:'lab'},
    {id:'p0_13',text:'Criar conta no GitHub e publicar primeiro repositório',tag:'proj'},
    {id:'p0_14',text:'Lab Packet Tracer: montar topologia de rede',tag:'lab'},
  ]},
  {id:'p1', label:'Fase 1 — Cloud + Docker', color:'#4d9fff', period:'Meses 5–9', items:[
    {id:'p1_01',text:'Azure: criar conta free tier e explorar portal',tag:'lab'},
    {id:'p1_02',text:'Azure: criar e configurar VM via SSH',tag:'lab'},
    {id:'p1_03',text:'Azure: Virtual Networks, subnets e NSGs',tag:'lab'},
    {id:'p1_04',text:'Azure: Storage Accounts e Blob Storage',tag:'lab'},
    {id:'p1_05',text:'Azure: IAM — usuários, grupos e políticas',tag:'teoria'},
    {id:'p1_06',text:'Azure: completar curso Udemy',tag:'lab'},
    {id:'p1_07',text:'Python infra: script com request HTTP',tag:'lab'},
    {id:'p1_08',text:'Python infra: automatizar tarefa no VPS da Famart',tag:'proj'},
    {id:'p1_09',text:'Git: commit, branch, merge e pull request',tag:'lab'},
    {id:'p1_10',text:'Git: publicar 2 projetos no GitHub com README',tag:'proj'},
    {id:'p1_11',text:'Docker: entender imagens, containers e Dockerfile',tag:'teoria'},
    {id:'p1_12',text:'Docker: docker run, build, push e registry',tag:'lab'},
    {id:'p1_13',text:'Docker: criar docker-compose com app + banco',tag:'lab'},
    {id:'p1_14',text:'Docker: publicar projeto Docker no GitHub',tag:'proj'},
    {id:'p1_15',text:'AZ-900: completar módulos Microsoft Learn',tag:'teoria'},
    {id:'p1_16',text:'AZ-900: simulados — atingir 85%+ de acerto',tag:'lab'},
    {id:'p1_17',text:'AZ-900: agendar e realizar o exame ✓',tag:'cert'},
  ]},
  {id:'p2', label:'Fase 2 — Especialização', color:'#ffb830', period:'Meses 10–18', items:[
    {id:'p2_01',text:'Terraform: instalar e entender HCL básico',tag:'teoria'},
    {id:'p2_02',text:'Terraform: provisionar VM e VNet na Azure',tag:'lab'},
    {id:'p2_03',text:'Terraform: state, variáveis e módulos',tag:'lab'},
    {id:'p2_04',text:'Terraform: projeto completo de infra versionada',tag:'proj'},
    {id:'p2_05',text:'Ansible: instalar e criar primeiro playbook',tag:'lab'},
    {id:'p2_06',text:'Ansible: configurar servidor com roles e handlers',tag:'lab'},
    {id:'p2_07',text:'Ansible: inventário dinâmico com Azure',tag:'lab'},
    {id:'p2_08',text:'Python avançado: Paramiko — SSH automatizado',tag:'lab'},
    {id:'p2_09',text:'Python avançado: script de monitoramento',tag:'proj'},
    {id:'p2_10',text:'CI/CD: pipeline GitHub Actions para deploy no VPS',tag:'lab'},
    {id:'p2_11',text:'CI/CD: pipeline com lint, test e deploy automático',tag:'lab'},
    {id:'p2_12',text:'AZ-104: VMs, armazenamento e redes',tag:'teoria'},
    {id:'p2_13',text:'AZ-104: identidade, governança e monitoramento',tag:'teoria'},
    {id:'p2_14',text:'AZ-104: simulados — atingir 85%+ de acerto',tag:'lab'},
    {id:'p2_15',text:'AZ-104: agendar e realizar o exame ✓',tag:'cert'},
    {id:'p2_16',text:'Portfólio: infra completa Terraform+Ansible+CI/CD',tag:'proj'},
  ]},
  {id:'p3', label:'Fase 3 — Nível sênior', color:'#a78bfa', period:'Meses 19–24', items:[
    {id:'p3_01',text:'Kubernetes: instalar Minikube e entender arquitetura',tag:'teoria'},
    {id:'p3_02',text:'Kubernetes: Pods, Deployments e Services',tag:'lab'},
    {id:'p3_03',text:'Kubernetes: Ingress, ConfigMaps e Secrets',tag:'lab'},
    {id:'p3_04',text:'Kubernetes: cluster AKS no Azure',tag:'lab'},
    {id:'p3_05',text:'Kubernetes: Helm charts e gestão de pacotes',tag:'lab'},
    {id:'p3_06',text:'Observabilidade: Prometheus + Grafana no Docker',tag:'lab'},
    {id:'p3_07',text:'Observabilidade: Azure Monitor e Log Analytics',tag:'lab'},
    {id:'p3_08',text:'Observabilidade: criar dashboards de infra reais',tag:'proj'},
    {id:'p3_09',text:'Cloud security: IAM avançado e zero trust',tag:'teoria'},
    {id:'p3_10',text:'Cloud security: SIEM e compliance',tag:'teoria'},
    {id:'p3_11',text:'FinOps: análise e otimização de custos cloud',tag:'teoria'},
    {id:'p3_12',text:'Projeto final: app com K8s + monitoramento + CI/CD',tag:'proj'},
    {id:'p3_13',text:'CKA ou AZ-305: simulados — 85%+ de acerto',tag:'lab'},
    {id:'p3_14',text:'CKA ou AZ-305: agendar e realizar o exame ✓',tag:'cert'},
  ]},
];

const WEEK_SCHEDULE = [
  {name:'Segunda', tema:'Redes / Teoria',  detalhe:'Aula do curso ou módulo teórico do dia'},
  {name:'Terça',   tema:'Python / Lab',    detalhe:'Prática de código ou exercícios'},
  {name:'Quarta',  tema:'Cloud / Lab',     detalhe:'Lab Azure, Docker ou ferramentas IaC'},
  {name:'Quinta',  tema:'Linux / Infra',   detalhe:'Terminal, automação, scripts'},
  {name:'Sexta',   tema:'Projeto',         detalhe:'Publicar algo concreto no GitHub'},
];
